### ISSUE TITLE
IOS IPAD: No drawn items by using IITC-CE instaed of IITC-ME

### ISSUE THREAD

**Issue by DF3IAP** [HubertZhang/IITC-Mobile#8]
Using IITC-CE, every item has gone: so i see an "empty" map, just with portal names on it (If I'm activating "Show Portal names")

I already Re-installed everything, but as soon as i'm activating IITC-CE release build / beta build / test build at "Settings -> Change IITC version), i got a "blank" map.
On 2 different iPad (V4 + V5, IOS 14.x and 15.1, 12.9" screen) i got this issue, 
if I'm switching to IITC-ME  , i do see everything (Portal "dot", links fields, portal names, ) but can't draw something with draw tools.

**Comment by HubertZhang** [comment]
Fixed by reduce RENDERER_PADDING

**Comment by aokie** [comment]
It is good at startup, but when you reload WebView, this issue still happens.

**Comment by homanw104** [comment]
The issue still persists in the latest version (as of 2024-02-23).
Overlays are only loaded when using IITC.me scripts.

Device: iPad Pro (11 inch) (2nd Generation)
System: iPadOS 17.2 (21C62)

******

Update: The issue no longer occurs after upgrading to iPadOS 18.
