### ISSUE TITLE
iOS, can no longer export

### ISSUE THREAD

**Issue by Jo0Lz** [HubertZhang/IITC-Mobile#9]
I'm running the latest version, but when I try to export anything to a file (Bookmarks, draw links, or 'all data') the app doesn't provide any file.
It's saving to files/dropbox, and when I e-mail it there is no attachment.

I'm running iOS 15.5. Please help :(

(Also, searching in the plugin screen crashes the app)

**Comment by HubertZhang** [comment]
Could you try testflight version? These bugs have been fixed.

**Comment by NvlblNm** [comment]
Export is not working on the TestFlight version either. I don’t know if `saveFile` is fixed in the latest version of IITC-CE, but it is still broken on the 3 versions in the current app: 0.32.1, 0.32.1.20211215.185651 [test], and 0.32.1.20211217.151857 [beta]

**Comment by HubertZhang** [comment]
The problem should be fixed in latest testflight version.
